<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Mobile Platform Macro -->
  <xacro:macro name="mobile_platform" params="prefix">

    <!-- Platform properties -->
    <xacro:property name="platform_length" value="1.0"/>
    <xacro:property name="platform_width" value="0.8"/>
    <xacro:property name="platform_height" value="0.15"/>
    <xacro:property name="platform_mass" value="50.0"/>

    <!-- Material for platform -->
    <material name="DarkGrey">
      <color rgba="0.3 0.3 0.3 1.0"/>
    </material>

    <!-- Fixed world link (ground reference) -->
    <link name="${prefix}world_platform">
      <inertial>
        <mass value="0.001"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001"/>
      </inertial>
    </link>

    <!-- Platform base link (moves along rail) -->
    <link name="${prefix}platform_base">
      <visual>
        <geometry>
          <box size="${platform_length} ${platform_width} ${platform_height}"/>
        </geometry>
        <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <geometry>
          <box size="${platform_length} ${platform_width} ${platform_height}"/>
        </geometry>
        <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${platform_mass}"/>
        <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
        <inertia ixx="${(1/12) * platform_mass * (platform_width*platform_width + platform_height*platform_height)}" 
                 ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * platform_mass * (platform_length*platform_length + platform_height*platform_height)}" 
                 iyz="0.0"
                 izz="${(1/12) * platform_mass * (platform_length*platform_length + platform_width*platform_width)}"/>
      </inertial>
    </link>

    <!-- Wheel properties -->
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="wheel_mass" value="2.0"/>
    <xacro:property name="wheel_offset_x" value="0.4"/>
    <xacro:property name="wheel_offset_y" value="0.35"/>

    <!-- Wheel macro -->
    <xacro:macro name="platform_wheel" params="wheel_prefix x_pos y_pos">
      <link name="${prefix}${wheel_prefix}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <material name="Black">
            <color rgba="0.1 0.1 0.1 1.0"/>
          </material>
        </visual>
        <collision>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          </geometry>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
        <inertial>
          <mass value="${wheel_mass}"/>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
          <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
                   ixy="0.0" ixz="0.0"
                   iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
                   iyz="0.0"
                   izz="${0.5 * wheel_mass * wheel_radius * wheel_radius}"/>
        </inertial>
      </link>

      <joint name="${prefix}${wheel_prefix}_wheel_joint" type="fixed">
        <parent link="${prefix}platform_base"/>
        <child link="${prefix}${wheel_prefix}_wheel"/>
        <origin xyz="${x_pos} ${y_pos} ${wheel_radius - platform_height/2}" rpy="0 0 0"/>
      </joint>

      <gazebo reference="${prefix}${wheel_prefix}_wheel">
        <material>Gazebo/Black</material>
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
      </gazebo>
    </xacro:macro>

    <!-- Instantiate 4 wheels -->
    <xacro:platform_wheel wheel_prefix="front_left" x_pos="${wheel_offset_x}" y_pos="${wheel_offset_y}"/>
    <xacro:platform_wheel wheel_prefix="front_right" x_pos="${wheel_offset_x}" y_pos="${-wheel_offset_y}"/>
    <xacro:platform_wheel wheel_prefix="rear_left" x_pos="${-wheel_offset_x}" y_pos="${wheel_offset_y}"/>
    <xacro:platform_wheel wheel_prefix="rear_right" x_pos="${-wheel_offset_x}" y_pos="${-wheel_offset_y}"/>

    <!-- Prismatic joint for linear motion (0 to 10 meters along X axis) -->
    <joint name="${prefix}platform_joint" type="prismatic">
      <parent link="${prefix}world_platform"/>
      <child link="${prefix}platform_base"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>  <!-- Motion along X axis -->
      <limit lower="0.0" upper="10.0" effort="1000.0" velocity="1.0"/>
      <dynamics damping="50.0" friction="10.0"/>
    </joint>

    <!-- Robot mounting plate on top of platform -->
    <link name="${prefix}robot_mount">
      <visual>
        <geometry>
          <cylinder radius="0.2" length="0.05"/>
        </geometry>
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.2" length="0.05"/>
        </geometry>
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="5.0"/>
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
        <inertia ixx="0.0208" ixy="0.0" ixz="0.0"
                 iyy="0.0208" iyz="0.0"
                 izz="0.02"/>
      </inertial>
    </link>

    <!-- Fixed joint connecting platform to robot mount -->
    <joint name="${prefix}platform_to_mount" type="fixed">
      <parent link="${prefix}platform_base"/>
      <child link="${prefix}robot_mount"/>
      <origin xyz="0 0 ${platform_height}" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo properties -->
    <gazebo reference="${prefix}world_platform">
      <static>true</static>
    </gazebo>

    <gazebo reference="${prefix}platform_base">
      <material>Gazebo/DarkGrey</material>
      <mu1>0.8</mu1>
      <mu2>0.8</mu2>
    </gazebo>

    <gazebo reference="${prefix}robot_mount">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Transmission for the prismatic joint -->
    <transmission name="${prefix}platform_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}platform_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}platform_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

</robot>
